ateliersoude/event/urls.py
from django.urls import path

from . import views

app_name = "event"


urlpatterns = [
    path(
        "condition/create/<int:orga_pk>/",
        views.ConditionCreateView.as_view(),
        name="condition_create",
    ),
    path(
        "condition/<int:pk>/edit/",
        views.ConditionEditView.as_view(),
        name="condition_edit",
    ),
    path(
        "condition/<int:pk>/delete/",
        views.ConditionDeleteView.as_view(),
        name="condition_delete",
    ),
    path("activity/", views.ActivityListView.as_view(), name="activity_list"),
    path(
        "activity/create/<int:orga_pk>/",
        views.ActivityCreateView.as_view(),
        name="activity_create",
    ),
    path(
        "activity/<int:pk>/edit/",
        views.ActivityEditView.as_view(),
        name="activity_edit",
    ),
    path(
        "activity/<int:pk>/delete/",
        views.ActivityDeleteView.as_view(),
        name="activity_delete",
    ),
    path(
        "activity/<int:pk>/<slug>/",
        views.ActivityView.as_view(),
        name="activity_detail",
    ),
    path("", views.EventListView.as_view(), name="list"),
    path(
        "create/<int:orga_pk>/", views.EventCreateView.as_view(), name="create"
    ),
    path(
        "recurrent/create/<int:orga_pk>/",
        views.RecurrentEventCreateView.as_view(),
        name="recurrent_create",
    ),
    path("<int:pk>/edit/", views.EventEditView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.EventDeleteView.as_view(), name="delete"),
    path("<int:pk>/close/", views.CloseEventView.as_view(), name="close"),
    path(
        "<int:pk>/add_active/",
        views.AddActiveEventView.as_view(),
        name="add_active",
    ),
    path(
        "<int:pk>/remove_active/",
        views.RemoveActiveEventView.as_view(),
        name="remove_active",
    ),
    path("<int:pk>/close/", views.CloseEventView.as_view(), name="close"),
    path("<int:pk>/<slug>/", views.EventView.as_view(), name="detail"),
    path(
        "cancel_reservation/<token>/",
        views.CancelReservationView.as_view(),
        name="cancel_reservation",
    ),
    path("book/<token>/", views.BookView.as_view(), name="book"),
    path("absent/<token>/", views.AbsentView.as_view(), name="user_absent"),
]

ateliersoude/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path("", views.HomeView.as_view(), name="homepage"),
    path("user/", include("ateliersoude.user.urls", namespace="user")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("event/", include("ateliersoude.event.urls", namespace="event")),
    path(
        "location/",
        include("ateliersoude.location.urls", namespace="location"),
    ),
    path(
        "api/location/",
        include("ateliersoude.location.api_urls", namespace="api_location"),
    ),
    path(r"tinymce/", include("tinymce.urls")),
]

if settings.DEBUG:
    import debug_toolbar  # noqa

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls))
    ] + urlpatterns

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

ateliersoude/user/urls.py
from django.urls import path

from . import views

app_name = "user"
urlpatterns = [
    path("", views.UserListView.as_view(), name="user_list"),
    path("<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path(
        "update/<int:pk>", views.UserUpdateView.as_view(), name="user_update"
    ),
    path("create/", views.UserCreateView.as_view(), name="user_create"),
    path(
        "create_and_book/",
        views.UserCreateAndBookView.as_view(),
        name="create_and_book",
    ),
    path(
        "organizations/",
        views.OrganizationListView.as_view(),
        name="organization_list",
    ),
    path(
        "organization/create/",
        views.OrganizationCreateView.as_view(),
        name="organization_create",
    ),
    path(
        "organization/<int:pk>/update/",
        views.OrganizationUpdateView.as_view(),
        name="organization_update",
    ),
    path(
        "organization/<int:orga_pk>/<slug>/events/<int:page>/",
        views.OrganizationEventsListView.as_view(),
        name="organization_all_events",
    ),
    path(
        "organization/<int:pk>/<slug>/",
        views.OrganizationDetailView.as_view(),
        name="organization_detail",
    ),
    path(
        "organization/<int:pk>/",
        views.OrganizationDeleteView.as_view(),
        name="organization_delete",
    ),
    path(
        "organization/<int:pk>/add-admin",
        views.AddAdminToOrganization.as_view(),
        name="organization_add_admin",
    ),
    path(
        "organization/<int:pk>/add-active",
        views.AddActiveToOrganization.as_view(),
        name="organization_add_active",
    ),
    path(
        "organization/<int:pk>/add-volunteer",
        views.AddVolunteerToOrganization.as_view(),
        name="organization_add_volunteer",
    ),
    path(
        "organization/<int:pk>/<int:user_pk>/remove-from-actives",
        views.RemoveActiveFromOrganization.as_view(),
        name="remove_from_actives",
    ),
    path(
        "organization/<int:pk>/<int:user_pk>/remove-from-volunteers",
        views.RemoveVolunteerFromOrganization.as_view(),
        name="remove_from_volunteers",
    ),
    path(
        "organization/<int:pk>/<int:user_pk>/remove-from-admins",
        views.RemoveAdminFromOrganization.as_view(),
        name="remove_from_admins",
    ),
    path(
        "present/<int:pk>",
        views.PresentCreateUserView.as_view(),
        name="present_create_user",
    ),
    path(
        "present/<int:event_pk>/<int:pk>/",
        views.PresentMoreInfoView.as_view(),
        name="present_with_more_info",
    ),
    path(
        "organization/<int:pk>/add-member",
        views.AddMemberToOrganization.as_view(),
        name="organization_add_member",
    ),
    path(
        "organization/<int:orga_pk>/update-member/<int:pk>",
        views.UpdateMemberView.as_view(),
        name="organization_update_member",
    ),
]

ateliersoude/event/models.py
from datetime import date, datetime, timedelta

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
from simple_history.models import HistoricalRecords

from ateliersoude.fields import CleanHTMLField

from ateliersoude.location.models import Place
from ateliersoude.user.models import CustomUser, Organization
from ateliersoude.utils import get_future_published_events, validate_image


class Condition(models.Model):
    name = models.CharField(verbose_name=_("Condition Type"), max_length=100)
    description = CleanHTMLField(
        verbose_name=_("Condition description"), default=""
    )
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="conditions"
    )
    price = models.FloatField(verbose_name=_("Price"), default=5)
    history = HistoricalRecords()

    def get_absolute_url(self):
        return reverse(
            "user:organization_detail",
            kwargs={
                "pk": self.organization.pk,
                "slug": self.organization.slug,
            },
        )

    def __str__(self):
        if self.price > 0:
            return f"{self.name} - {self.price}€"
        return self.name


class Activity(models.Model):
    name = models.CharField(verbose_name=_("Activity type"), max_length=100)
    slug = models.SlugField(blank=True)
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="activities"
    )
    description = CleanHTMLField(
        verbose_name=_("Activity description"), default=""
    )
    picture = models.ImageField(
        verbose_name=_("Image"),
        upload_to="activities/",
        blank=True,
        null=True,
        validators=[validate_image],
    )
    history = HistoricalRecords()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("event:activity_detail", args=(self.pk, self.slug))

    def next_events(self):
        return get_future_published_events(self.events)


class Event(models.Model):
    WEEKS = [
        (1, "Semaine 1"),
        (2, "Semaine 2"),
        (3, "Semaine 3"),
        (4, "Semaine 4"),
        (5, "Semaine 5"),
    ]
    DAYS = [
        ("MO", "Lundi"),
        ("TU", "Mardi"),
        ("WE", "Mercredi"),
        ("TH", "Jeudi"),
        ("FR", "Vendredi"),
        ("SA", "Samedi"),
        ("SU", "Dimanche"),
    ]

    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="events"
    )
    conditions = models.ManyToManyField(
        Condition,
        related_name="events",
        verbose_name=_("Conditions"),
        blank=True,
    )
    published = models.BooleanField(verbose_name=_("Published"), default=False)
    publish_at = models.DateTimeField(
        verbose_name=_("Publication date and time"), default=timezone.now
    )
    activity = models.ForeignKey(
        Activity, on_delete=models.SET_NULL, null=True, related_name="events"
    )
    slug = models.SlugField(blank=True)
    date = models.DateField(verbose_name=_("Event day"), default=date.today)
    starts_at = models.TimeField(
        verbose_name=_("Start time"), default=timezone.now
    )
    ends_at = models.TimeField(verbose_name=_("End time"))
    available_seats = models.PositiveIntegerField(
        verbose_name=_("Available seats"), default=0
    )
    registered = models.ManyToManyField(
        CustomUser,
        related_name="registered_events",
        verbose_name=_("Registered"),
        blank=True,
    )
    presents = models.ManyToManyField(
        CustomUser,
        related_name="presents_events",
        verbose_name=_("Presents"),
        blank=True,
        through="Participation",
    )
    organizers = models.ManyToManyField(
        CustomUser,
        related_name="organizers_events",
        verbose_name=_("Organizers"),
        blank=True,
    )
    location = models.ForeignKey(
        Place, on_delete=models.SET_NULL, null=True, related_name="events"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    history = HistoricalRecords()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.activity.name)
        return super().save(*args, kwargs)

    @property
    def remaining_seats(self):
        return self.available_seats - (
            self.registered.count() + self.presents.count()
        )

    def date_interval_format(self):
        date = self.date.strftime("%A %d %B")
        starts_at_time = self.starts_at.strftime("%H:%M")
        ends_at_time = self.ends_at.strftime("%H:%M")

        # ex Lundi 01 Janvier 2018 de 20:01:12 à 22:01:12
        return f"{date} de {starts_at_time} à {ends_at_time}"

    def get_absolute_url(self):
        return reverse("event:detail", args=(self.pk, self.slug))

    @property
    def has_ended(self):
        ends = datetime.combine(
            self.date, self.ends_at, tzinfo=timezone.now().tzinfo
        ) + timedelta(hours=4)
        return ends < timezone.now()

    @property
    def has_started(self):
        starts = datetime.combine(
            self.date, self.starts_at, tzinfo=timezone.now().tzinfo
        ) - timedelta(hours=2)
        return starts < timezone.now()

    @classmethod
    def future_published_events(cls):
        return get_future_published_events(cls.objects)

    def __str__(self):
        full_title = "%s du %s" % (
            self.activity.name,
            self.date.strftime("%d %B"),
        )
        return full_title


class Participation(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    event = models.ForeignKey(
        Event, on_delete=models.CASCADE, related_name="participations"
    )
    saved = models.BooleanField(default=False)
    amount = models.PositiveIntegerField(
        verbose_name=_("Amount paid"), default=0, blank=True
    )
    history = HistoricalRecords()

    class Meta:
        unique_together = (("user", "event"),)

ateliersoude/event/templates/event/event_cards.html
{% load thumbnail %}

{% for event in event_list %}
  <div class="card">
    {% if event.activity.picture %}
      {% thumbnail event.activity.picture "400" format="PNG" as im %}
        <img class="card-img-top rounded-0" src="{{ im.url }}"/>
      {% endthumbnail %}
    {% endif %}
    <div class="card-body">
      <h2 class="card-title">{{ event.activity.name }}</h2>
      <h6 class="card-subtitle text-muted mb-2">
        <small>
          {{ event.date_interval_format }}
        </small>
      </h6>
      <h6 class="card-subtitle text-muted mb-2">
        <small>
          {% if event.remaining_seats <= 0 %}
          <span class="badge badge-warning badge-pill">Complet</span>
          {% else %}
          Encore
          <span class="badge badge-info badge-pill">{{ event.remaining_seats }}
          </span> places disponibles
          {% endif %}
        </small>
      </h6>

      {{ event.activity.description | safe | truncatewords_html:10 }}
      <p>
      <a class="btn btn-info btn-sm" href="{% url 'event:detail' event.pk event.slug %}">
        <i class="fa fa-eye"></i>
        Voir l'évènement
      </a>
      {% if event.remaining_seats > 0 %}
        {% include "event/register.html" with event=event %}
      {% endif %}
      </p>
      <footer class="text-muted">
        {% if event.organization.picture %}
        {% thumbnail event.organization.picture "30x30" crop="left" format="PNG" as im %}
          <img class="img-fluid rounded-circle square-2" src="{{ im.url }}" alt="organization img">
        {% endthumbnail %}
        {% endif %}
        Organisé par '{{ event.organization }}' à '{{ event.location.name }}'
      </footer>
    </div>
  </div>
{% endfor %}

ateliersoude/event/templates/event/event_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  {% url "event:list" as event_list_url %}
  {% url "event:detail" event.pk event.slug as event_detail_url %}
  {% include "breadcrumb.html" with current="Suppression" second_parent_url=event_list_url second_parent_text="Évènements" first_parent_url=event_detail_url first_parent_text=event %}
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">
        Suppression de '{{ event }}'
      </h1>
    </div>
  </div>
  <section class="container">
    <p>
      <i class="fa fa-exclamation-triangle"></i>
      Vous êtes sur le point de supprimer l'évènement <code>'{{ event }}'</code> organisé par <code>'{{ event.organization }}'</code>. Êtes-vous certain de votre choix ?
    </p>
    <form method="post">{% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-danger" type="submit">
        <i class="fa fa-trash"></i>
        Oui je suis sûr
      </button>
      <a class="btn btn-success" href="{% url 'event:detail' event.pk event.slug %}">
        <i class="fa fa-arrow-left"></i>
        Non, revenir
      </a>
    </form>
  </section>
{% endblock %}

ateliersoude/event/templates/event/event_detail.html
{% extends 'base.html' %}
{% load assets l10n app_filters %}

{% block extra_css %}
  {% assets "css_detail_event" %}
    <link type="text/css" href="{{ ASSET_URL }}" rel="stylesheet"/>
  {% endassets %}
{% endblock %}

{% block content %}
  {% url "event:list" as event_list_url %}
  {% include "breadcrumb.html" with current=event first_parent_url=event_list_url first_parent_text="Évènements" %}
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">{{ event }}</h1>
      <p class="lead">
        - Organisé par
        <a href="{% url 'user:organization_detail' event.organization.id event.organization.slug %}">
          {{ event.organization.name }}
        </a>
      </p>
      <div class="lead">
      {% if is_active %}
        <a href="{% url 'event:edit' event.pk %}" class="btn btn-warning btn-sm">
          <i class="fa fa-pencil-alt"></i> Éditer
        </a>
      {% endif %}
      {% if is_admin %}
        <a href="{% url 'event:delete' event.pk %}" class="btn btn-danger btn-sm">
          <i class="fa fa-trash"></i> Supprimer
        </a>
      {% endif %}
      {% if is_active %}
        <form action="{% url 'event:close' event.pk %}" method="post" class="d-inline">
          {% csrf_token %}
          <button class="btn btn-sm btn-info btn-sm" type="submit" onclick="return confirm('Êtes-vous sûrs de vouloir clôturer l\'évènement?')">
            <i class="fa fa-calendar-check"></i>
            Clôturer
          </button>
        </form>
      {% endif %}
      </div>
    </div>
  </div>
  <section class="container">
    <div class="card">
      <div class="row pl-3 pr-3">
        <div class="card-body col-lg-6">
          <h6 class="card-subtitle text-muted pb-3">
            {% if event.remaining_seats == 0 %}
              <span class="badge badge-warning badge-pill">Complet</span>
            {% else %}
              Encore
              <span class="badge badge-info badge-pill">{{ event.remaining_seats }}
                </span> places disponibles
            {% endif %}
            {% if request.user in event.registered.all or request.user in event.presents.all %}
              <span class="badge badge-success badge-pill">Inscrit</span>
            {% endif %}
          </h6>

          {{ event.activity.description | safe }}
          <p>
            <i class="fa fa-calendar-alt"></i> 
            Début le {{ event.date_interval_format }} 
          </p>

          <hr>

          <b>Condition(s) de venue:</b>
          <ul class="pt-3">
            {% for condition in event.conditions.all %}
              <li>
                <span class="badge badge-pill badge-secondary">
                  {% if condition.price > 0 %}
                    {{ condition.price }}€
                  {% else %}
                    free
                  {% endif %}
                </span> -
                {{ condition.description | safe }}
              </li>
              {% empty %}
              <li>La participation est libre / pas de condition d'accès</li>
            {% endfor %}
          </ul>

          <a href="{% url 'event:activity_detail' event.activity.pk event.activity.slug %}" class="btn btn-info btn-sm">
            <i class="fa fa-eye"></i>
            En savoir plus sur l'activité
          </a>
          {% include "event/register.html" with event=event %}
          {% if is_active and user not in event.registered.all %}
            <form
                {% if user in event.organizers.all %}
                action="{% url 'event:remove_active' event.pk %}"
                {% else %}
                action="{% url 'event:add_active' event.pk %}"
                {% endif %}
                method="post"
                class="d-inline">
              {% csrf_token %}
              {% if user in event.organizers.all %}
              <button class="btn btn-sm btn-warning btn-sm" type="submit">
                Je n'organise plus
              </button>
              {% else %}
              <button class="btn btn-sm btn-info btn-sm" type="submit">
                J'organise
              </button>
              {% endif %}
            </form>

          {% endif %}
        </div>

        <div class="card-body col-lg-6 p-0">
          <div style="height:100%; min-height: 250px" id="event_map"></div>
        </div>
      </div>

      <div class="card-footer">
        <small>
          Organisé par
          <a href="{% url 'user:organization_detail' event.organization.id event.organization.slug %}">
            {{ event.organization.name }}
          </a>

          <br>
          <i class="fa fa-map-marker"></i>
          <a href="{% url 'location:detail' event.location.id event.location.slug %}">
            {{ event.location.name }}</a>,
          {{ event.location.address }}
        </small>
      </div>

      {% if event.activity.picture %}
        <img class="img-responsive w-100" src="{{ event.activity.picture.url }}" alt="activity illustration">
      {% endif %}
    </div>
  </section>

  <section class="container">
    <h5 class="mt-4">Animateur·trice·s</h5>
    <hr>

    <div class="row">
    {% for user in event.organizers.all %}
      <div class="col-md-4 col-lg-3 p-2">
        {% if not user.is_visible and not is_admin %}
          <div class="card">
            <div class="card-body text-center p-4">
              <i class="fa fa-user fa-4x"></i><br>
              {{ user }}
            </div>
          </div>
        {% else %}
          <div class="card">
            <a href="{% url "user:user_detail" user.pk %}" class="card-link">
              <div class="card-body text-center p-4">
                <i class="fa fa-user fa-4x"></i><br>
                {{ user }}
              </div>
            </a>
          </div>
        {% endif %}
      </div>
    {% endfor %}
    </div>

    {% if is_volunteer %}
      <h5 class="mt-4" id="manage">Pré-inscrit·e·s</h5>
      <hr>

      {% if event.remaining_seats > 0 and is_active %}
        {% include "event/register.html" with event=event admin_text="Préinscrire une personne" %}
      {% endif %}

    <div class="row">
      {% for user in event.registered.all %}
        <div class="col-md-4 col-lg-3 p-2">
          <div class="card">
            <div class="card-body text-center p-4">
              <a href="{% url "user:user_detail" user.pk %}" class="card-link">
                <i class="fa fa-user fa-4x"></i><br>
                {{ user }}
                <span class="badge badge-pill badge-primary">
                  {% filter_orga queryset=user.memberships organization=event.organization as membership %}
                  {% if membership %}
                    {{ membership.current_contribution }}
                  {% else %}
                    0
                  {% endif %}
                  €
                </span>
                <br>
              </a>
              {% if event.has_started and is_active %}
              {% include "event/modal_more_info.html" with anonymous_user=user form=present_form|initial:user %}
              {% endif %}
            </div>
          </div>
        </div>
      {% endfor %}
    </div>

      <h5 class="mt-4">Présent·e·s</h5>
      <hr>

      {% if event.has_started and is_active %}
        {% include "event/modal_more_info.html" with form=present_form admin_text="Ajouter un présent" %}
      {% endif %}

    <div class="row">
      {% for participation in event.participations.all %}
        <div class="col-md-4 col-lg-3 p-2">
          <div class="card">
            <div class="card-body text-center p-4">
              <a href="{% url "user:user_detail" participation.user.pk %}" class="card-link">
                <i class="fa fa-user fa-4x"></i><br>
                {{ participation.user }}
                <span class="badge badge-pill badge-primary">
                  {% filter_orga queryset=participation.user.memberships organization=event.organization as membership %}
                  {% if membership %}
                    {{ membership.current_contribution }}
                  {% else %}
                    0
                  {% endif %}
                  €
                </span>
                {% if participation.amount > 0 %}
                  <span class="badge badge-pill badge-secondary">
                  + {{ participation.amount }}€
                  </span>
                {% endif %}
                <br>
              </a>
              {% if is_active %}
                {% tokenize user=participation.user event=event action='absent' as tok %}
                <a href="{% url 'event:user_absent' tok %}" class="btn btn-danger btn-sm">
                  <i class="fa fa-minus"></i>
                  Marquer en absent
                </a>
              {% endif %}
            </div>
          </div>
        </div>
      {% endfor %}
    </div>

    <h5 class="mt-4">Quelques statistiques sur l'évènement</h5>
    <hr>
    <ul>
    <li>Total des cotisations perçues: {{ total_fees }}€</li>
    <li>Membres présents : {{ event.presents.all|length }}</li>
    <li>Nombre d'organisateurs: {{ event.organizers.all|length }}</li>
    </ul>

    {% endif %}

  </section>

{% endblock %}

{% block extra_js %}
  {{ users|json_script:"users-data" }}
  <script>
      const longitude = {{ event.location.longitude|unlocalize }};
      const latitude = {{ event.location.latitude|unlocalize }};
  </script>
  {% assets "js_detail_event" %}
    <script src="{{ ASSET_URL }}"></script>
  {% endassets %}
{% endblock %}

ateliersoude/event/templates/event/modal_more_info.html
{% load bootstrap4 app_filters %}

<button class="btn btn-success btn-sm" data-toggle="modal" data-target="#more-info-{{ anonymous_user.pk }}">
  <i class="fa fa-plus"></i>
  {% if admin_text %}
    {{ admin_text }}
  {% else %}
    Marquer en présent
  {% endif %}
</button>
<div class="modal" id="more-info-{{ anonymous_user.pk }}" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          {% if anonymous_user %}
            Compléter les info de {{ anonymous_user }}
          {% else %}
            Marquer quelqu'un en "présent" pour l'évènement
          {% endif %}
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Nous devons garder une trace des personnes présentes aux ateliers, veuillez compléter ces info svp
        <form
            {% if anonymous_user %}
              action="{% url 'user:present_with_more_info' event.pk anonymous_user.pk %}"
            {% else %}
              action="{% url 'user:present_create_user' event.pk %}"
            {% endif %}
              method="post"
              class="text-left"
        >
          <div class="modal-body">
            {% csrf_token %}
            {% bootstrap_form form=form %}
          </div>
          <b>Note(s) :</b>
          <ul>
            <li>
              La contribution minimale pour cette organisation est de
              <span class="badge badge-pill badge-secondary">{{ event.organization.min_fee }}€</span>
              et la contribution totale conseillée est de
              <span class="badge badge-pill badge-success">{{ event.organization.advised_fee }}€</span>
            </li>
            {% if event.organization.fee_description %}
              <li>{{ event.organization.fee_description }}</li>
            {% endif %}
            {% if anonymous_user and anonymous_user.first_name %}
              <li>
                {% filter_orga queryset=user.memberships organization=event.organization as membership %}
                {% if membership %}
                  {{ anonymous_user }} a payé <b>{{ membership.current_contribution }}€</b> depuis le {{ membership.first_payment|date:"d F Y" }}
                {% else %}
                  {{ anonymous_user }} n'a pas encore contribué pour <span class="badge badge-pill badge-primary">{{ event.organization }}</span>
                {% endif %}
              </li>
            {% endif %}
          </ul>
          <div class="modal-footer">
            <input type="submit" value="Enregistrer" class="btn btn-primary">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

ateliersoude/event/templates/event/register.html
{% load app_filters bootstrap4 %}

{% if admin_text or not request.user.is_authenticated %}
  <button class="btn btn-success btn-sm" data-toggle="modal" data-target="#reservation{{ event.pk }}">
  {% if admin_text %}
  <i class="fa fa-plus"></i>
    {{ admin_text }}
  {% else %}
    Je participe !
  {% endif %}
  </button>
  <div class="modal" id="reservation{{ event.pk }}" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Réserver</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{% url 'user:create_and_book' %}?event={{ event.pk }}" method="post">
          <div class="modal-body">
            {% csrf_token %}
            {% bootstrap_form form=register_form %}
          </div>
          <div class="modal-footer">
            <input type="submit" value="Réserver" class="btn btn-primary"/>
          </div>
        </form>
      </div>
    </div>
  </div>
{% else %}
  {% if request.user in event.registered.all %}
    {% tokenize user=request.user event=event action='cancel' as tok %}
    <a href="{% url 'event:cancel_reservation' tok %}" class="btn btn-warning btn-sm">Je ne participe plus</a>
  {% elif request.user not in event.presents.all and request.user not in event.organizers.all %}
    {% tokenize user=request.user event=event action='book' as tok %}
    <a href="{% url 'event:book' tok %}" class="btn btn-success btn-sm">Je participe !</a>
  {% endif %}
{% endif %}