ateliersoude/event/urls.py
from django.urls import path

from . import views

app_name = "event"


urlpatterns = [
    path(
        "condition/create/<int:orga_pk>/",
        views.ConditionCreateView.as_view(),
        name="condition_create",
    ),
    path(
        "condition/<int:pk>/edit/",
        views.ConditionEditView.as_view(),
        name="condition_edit",
    ),
    path(
        "condition/<int:pk>/delete/",
        views.ConditionDeleteView.as_view(),
        name="condition_delete",
    ),
    path("activity/", views.ActivityListView.as_view(), name="activity_list"),
    path(
        "activity/create/<int:orga_pk>/",
        views.ActivityCreateView.as_view(),
        name="activity_create",
    ),
    path(
        "activity/<int:pk>/edit/",
        views.ActivityEditView.as_view(),
        name="activity_edit",
    ),
    path(
        "activity/<int:pk>/delete/",
        views.ActivityDeleteView.as_view(),
        name="activity_delete",
    ),
    path(
        "activity/<int:pk>/<slug>/",
        views.ActivityView.as_view(),
        name="activity_detail",
    ),
    path("", views.EventListView.as_view(), name="list"),
    path(
        "create/<int:orga_pk>/", views.EventCreateView.as_view(), name="create"
    ),
    path(
        "recurrent/create/<int:orga_pk>/",
        views.RecurrentEventCreateView.as_view(),
        name="recurrent_create",
    ),
    path("<int:pk>/edit/", views.EventEditView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.EventDeleteView.as_view(), name="delete"),
    path("<int:pk>/close/", views.CloseEventView.as_view(), name="close"),
    path(
        "<int:pk>/add_active/",
        views.AddActiveEventView.as_view(),
        name="add_active",
    ),
    path(
        "<int:pk>/remove_active/",
        views.RemoveActiveEventView.as_view(),
        name="remove_active",
    ),
    path("<int:pk>/close/", views.CloseEventView.as_view(), name="close"),
    path("<int:pk>/<slug>/", views.EventView.as_view(), name="detail"),
    path(
        "cancel_reservation/<token>/",
        views.CancelReservationView.as_view(),
        name="cancel_reservation",
    ),
    path("book/<token>/", views.BookView.as_view(), name="book"),
    path("absent/<token>/", views.AbsentView.as_view(), name="user_absent"),
]

ateliersoude/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path("", views.HomeView.as_view(), name="homepage"),
    path("user/", include("ateliersoude.user.urls", namespace="user")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("event/", include("ateliersoude.event.urls", namespace="event")),
    path(
        "location/",
        include("ateliersoude.location.urls", namespace="location"),
    ),
    path(
        "api/location/",
        include("ateliersoude.location.api_urls", namespace="api_location"),
    ),
    path(r"tinymce/", include("tinymce.urls")),
]

if settings.DEBUG:
    import debug_toolbar  # noqa

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls))
    ] + urlpatterns

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

ateliersoude/user/urls.py
from django.urls import path

from . import views

app_name = "user"
urlpatterns = [
    path("", views.UserListView.as_view(), name="user_list"),
    path("<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path(
        "update/<int:pk>", views.UserUpdateView.as_view(), name="user_update"
    ),
    path("create/", views.UserCreateView.as_view(), name="user_create"),
    path(
        "create_and_book/",
        views.UserCreateAndBookView.as_view(),
        name="create_and_book",
    ),
    path(
        "organizations/",
        views.OrganizationListView.as_view(),
        name="organization_list",
    ),
    path(
        "organization/create/",
        views.OrganizationCreateView.as_view(),
        name="organization_create",
    ),
    path(
        "organization/<int:pk>/update/",
        views.OrganizationUpdateView.as_view(),
        name="organization_update",
    ),
    path(
        "organization/<int:orga_pk>/<slug>/events/<int:page>/",
        views.OrganizationEventsListView.as_view(),
        name="organization_all_events",
    ),
    path(
        "organization/<int:pk>/<slug>/",
        views.OrganizationDetailView.as_view(),
        name="organization_detail",
    ),
    path(
        "organization/<int:pk>/",
        views.OrganizationDeleteView.as_view(),
        name="organization_delete",
    ),
    path(
        "organization/<int:pk>/add-admin",
        views.AddAdminToOrganization.as_view(),
        name="organization_add_admin",
    ),
    path(
        "organization/<int:pk>/add-active",
        views.AddActiveToOrganization.as_view(),
        name="organization_add_active",
    ),
    path(
        "organization/<int:pk>/add-volunteer",
        views.AddVolunteerToOrganization.as_view(),
        name="organization_add_volunteer",
    ),
    path(
        "organization/<int:pk>/<int:user_pk>/remove-from-actives",
        views.RemoveActiveFromOrganization.as_view(),
        name="remove_from_actives",
    ),
    path(
        "organization/<int:pk>/<int:user_pk>/remove-from-volunteers",
        views.RemoveVolunteerFromOrganization.as_view(),
        name="remove_from_volunteers",
    ),
    path(
        "organization/<int:pk>/<int:user_pk>/remove-from-admins",
        views.RemoveAdminFromOrganization.as_view(),
        name="remove_from_admins",
    ),
    path(
        "present/<int:pk>",
        views.PresentCreateUserView.as_view(),
        name="present_create_user",
    ),
    path(
        "present/<int:event_pk>/<int:pk>/",
        views.PresentMoreInfoView.as_view(),
        name="present_with_more_info",
    ),
    path(
        "organization/<int:pk>/add-member",
        views.AddMemberToOrganization.as_view(),
        name="organization_add_member",
    ),
    path(
        "organization/<int:orga_pk>/update-member/<int:pk>",
        views.UpdateMemberView.as_view(),
        name="organization_update_member",
    ),
]

ateliersoude/event/models.py
from datetime import date, datetime, timedelta

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
from simple_history.models import HistoricalRecords

from ateliersoude.fields import CleanHTMLField

from ateliersoude.location.models import Place
from ateliersoude.user.models import CustomUser, Organization
from ateliersoude.utils import get_future_published_events, validate_image


class Condition(models.Model):
    name = models.CharField(verbose_name=_("Condition Type"), max_length=100)
    description = CleanHTMLField(
        verbose_name=_("Condition description"), default=""
    )
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="conditions"
    )
    price = models.FloatField(verbose_name=_("Price"), default=5)
    history = HistoricalRecords()

    def get_absolute_url(self):
        return reverse(
            "user:organization_detail",
            kwargs={
                "pk": self.organization.pk,
                "slug": self.organization.slug,
            },
        )

    def __str__(self):
        if self.price > 0:
            return f"{self.name} - {self.price}€"
        return self.name


class Activity(models.Model):
    name = models.CharField(verbose_name=_("Activity type"), max_length=100)
    slug = models.SlugField(blank=True)
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="activities"
    )
    description = CleanHTMLField(
        verbose_name=_("Activity description"), default=""
    )
    picture = models.ImageField(
        verbose_name=_("Image"),
        upload_to="activities/",
        blank=True,
        null=True,
        validators=[validate_image],
    )
    history = HistoricalRecords()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("event:activity_detail", args=(self.pk, self.slug))

    def next_events(self):
        return get_future_published_events(self.events)


class Event(models.Model):
    WEEKS = [
        (1, "Semaine 1"),
        (2, "Semaine 2"),
        (3, "Semaine 3"),
        (4, "Semaine 4"),
        (5, "Semaine 5"),
    ]
    DAYS = [
        ("MO", "Lundi"),
        ("TU", "Mardi"),
        ("WE", "Mercredi"),
        ("TH", "Jeudi"),
        ("FR", "Vendredi"),
        ("SA", "Samedi"),
        ("SU", "Dimanche"),
    ]

    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="events"
    )
    conditions = models.ManyToManyField(
        Condition,
        related_name="events",
        verbose_name=_("Conditions"),
        blank=True,
    )
    published = models.BooleanField(verbose_name=_("Published"), default=False)
    publish_at = models.DateTimeField(
        verbose_name=_("Publication date and time"), default=timezone.now
    )
    activity = models.ForeignKey(
        Activity, on_delete=models.SET_NULL, null=True, related_name="events"
    )
    slug = models.SlugField(blank=True)
    date = models.DateField(verbose_name=_("Event day"), default=date.today)
    starts_at = models.TimeField(
        verbose_name=_("Start time"), default=timezone.now
    )
    ends_at = models.TimeField(verbose_name=_("End time"))
    available_seats = models.PositiveIntegerField(
        verbose_name=_("Available seats"), default=0
    )
    registered = models.ManyToManyField(
        CustomUser,
        related_name="registered_events",
        verbose_name=_("Registered"),
        blank=True,
    )
    presents = models.ManyToManyField(
        CustomUser,
        related_name="presents_events",
        verbose_name=_("Presents"),
        blank=True,
        through="Participation",
    )
    organizers = models.ManyToManyField(
        CustomUser,
        related_name="organizers_events",
        verbose_name=_("Organizers"),
        blank=True,
    )
    location = models.ForeignKey(
        Place, on_delete=models.SET_NULL, null=True, related_name="events"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    history = HistoricalRecords()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.activity.name)
        return super().save(*args, kwargs)

    @property
    def remaining_seats(self):
        return self.available_seats - (
            self.registered.count() + self.presents.count()
        )

    def date_interval_format(self):
        date = self.date.strftime("%A %d %B")
        starts_at_time = self.starts_at.strftime("%H:%M")
        ends_at_time = self.ends_at.strftime("%H:%M")

        # ex Lundi 01 Janvier 2018 de 20:01:12 à 22:01:12
        return f"{date} de {starts_at_time} à {ends_at_time}"

    def get_absolute_url(self):
        return reverse("event:detail", args=(self.pk, self.slug))

    @property
    def has_ended(self):
        ends = datetime.combine(
            self.date, self.ends_at, tzinfo=timezone.now().tzinfo
        ) + timedelta(hours=4)
        return ends < timezone.now()

    @property
    def has_started(self):
        starts = datetime.combine(
            self.date, self.starts_at, tzinfo=timezone.now().tzinfo
        ) - timedelta(hours=2)
        return starts < timezone.now()

    @classmethod
    def future_published_events(cls):
        return get_future_published_events(cls.objects)

    def __str__(self):
        full_title = "%s du %s" % (
            self.activity.name,
            self.date.strftime("%d %B"),
        )
        return full_title


class Participation(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    event = models.ForeignKey(
        Event, on_delete=models.CASCADE, related_name="participations"
    )
    saved = models.BooleanField(default=False)
    amount = models.PositiveIntegerField(
        verbose_name=_("Amount paid"), default=0, blank=True
    )
    history = HistoricalRecords()

    class Meta:
        unique_together = (("user", "event"),)

ateliersoude/user/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import CustomUser, Organization


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ["email"]


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = CustomUser


class UserCreateForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ["email", "first_name", "last_name", "street_address"]


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = [
            "email",
            "first_name",
            "last_name",
            "avatar_img",
            "phone_number",
            "street_address",
            "birth_date",
            "gender",
            "bio",
            "is_visible",
        ]
        widgets = {
            "birth_date": forms.DateInput(
                attrs={"type": "date"}, format="%Y-%m-%d"
            )
        }


class CustomUserEmailForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ["email"]


class MoreInfoCustomUserForm(forms.ModelForm):
    amount_paid = forms.IntegerField(min_value=0, initial=0)

    class Meta:
        model = CustomUser
        fields = ["email", "first_name", "last_name", "street_address"]


class OrganizationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["picture"].widget.attrs.update({"class": "form-control"})
        self.fields["fee_description"].widget = forms.TextInput()

    class Meta:
        model = Organization
        exclude = [
            "visitors",
            "members",
            "actives",
            "volunteers",
            "admins",
            "slug",
        ]

ateliersoude/user/templates/user/organization/confirmation_delete.html
{% extends 'base.html' %}

{% block content %}
  {% url "user:organization_list" as organization_list_url %}
  {% url "user:organization_detail" organization.pk organization.slug as organization_detail_url %}
  {% include "breadcrumb.html" with current="Suppression" second_parent_url=organization_list_url second_parent_text="Organisations" first_parent_url=organization_detail_url first_parent_text=organization %}

  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="mt-5">Suppression de '{{ organization }}'</h1>
    </div>
  </div>

  <section class="container">
    <p>
      <i class="fa fa-exclamation-triangle"></i>
      Vous êtes sur le point de supprimer l'organisation <code>'{{ organization }}'</code>. Êtes-vous certain de votre choix ?
    </p>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-danger" type="submit" value="Oui je suis sûr">
    </form>
  </section>
{% endblock %}

ateliersoude/user/templates/user/organization/manage_user.html
{% load bootstrap4 %}

<div class="row">
  
  <div class="col-xl mb-2">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Les administrateurs</h4>
        <ul class="list-group list-group-flush">
          {% for user in organization.admins.all %}
          <li class="list-group-item">
          {% if not user.is_visible and not is_admin %}
          {{ user }}
          {% else %}
          <a href="{% url 'user:user_detail' user.pk %}">
            {{ user }}
          </a>
          {% endif %}
          {% if is_admin %}
          <form action="{% url 'user:remove_from_admins' organization.pk user.pk %}" class="d-inline">
            {% csrf_token %}
            <button type="submit" class="btn badge badge-pill badge-danger" onclick="return confirm('Êtes-vous sûr ?')">&times;</button>
          </form>
          {% endif %}
          </li>
          {% empty %}
          <li class="list-group-item">
          Il n'y a pas d'administrateur associé à cette organisation.
          </li>
          {% endfor %}
        </ul>
        {% if is_admin %}
        <form class="mt-2" action="{% url 'user:organization_add_admin' organization.pk %}" method="post">
          {% csrf_token %}
          {% bootstrap_form add_admin_form %}
          <div class="form-group">
            <button type="submit" class="btn btn-success btn-block">
              <i class="fa fa-plus"></i>
              Ajouter cet admin
            </button>
          </div>
        </form>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="col-xl mb-2">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Les actifs</h4>
        <ul class="list-group list-group-flush">
          {% for user in organization.actives.all %}
          <li class="list-group-item">
          {% if not user.is_visible and not is_admin %}
            {{ user }}
          {% else %}
          <a href="{% url 'user:user_detail' user.pk %}">
            {{ user }}
          </a>
          {% endif %}
          {% if is_admin %}
          <form action="{% url 'user:remove_from_actives' organization.pk user.pk %}" class="d-inline">
            {% csrf_token %}
            <button type="submit" class="btn badge badge-pill badge-danger" onclick="return confirm('Êtes-vous sûr ?')">&times;</button>
          </form>
          {% endif %}
          </li>
          {% empty %}
          <li class="list-group-item">
          Il n'y a pas de membre volontaire associé à cette organisation.
          </li>
          {% endfor %}
        </ul>
        {% if is_active %}
        <form class="mt-2" action="{% url 'user:organization_add_active' organization.pk %}" method="post">
          {% csrf_token %}
          {% bootstrap_form add_active_form %}
          <div class="form-group">
            <button type="submit" class="btn btn-success btn-block">
              <i class="fa fa-plus"></i>
              Ajouter cet actif
            </button>
          </div>
        </form>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="col-xl mb-2">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Les volontaires</h4>
        <ul class="list-group list-group-flush">
          {% for user in organization.volunteers.all %}
          <li class="list-group-item">
          {% if not user.is_visible and not is_admin %}
          {{ user }}
          {% else %}
          <a href="{% url 'user:user_detail' user.pk %}">
            {{ user }}
          </a>
          {% endif %}
          {% if is_admin %}
          <form action="{% url 'user:remove_from_volunteers' organization.pk user.pk %}" class="d-inline">
            {% csrf_token %}
            <button type="submit" class="btn badge badge-pill badge-danger" onclick="return confirm('Êtes-vous sûr ?')">&times;</button>
          </form>
          {% endif %}
          </li>
          {% empty %}
          <li class="list-group-item">
          Il n'y a pas de volontaire associé à cette organisation.
          </li>
          {% endfor %}
        </ul>
        {% if is_active %}
        <form class="mt-2" action="{% url 'user:organization_add_volunteer' organization.pk %}" method="post">
          {% csrf_token %}
          {% bootstrap_form add_volunteer_form %}
          <div class="form-group">
            <button type="submit" class="btn btn-success btn-block">
              <i class="fa fa-plus"></i>
              Ajouter ce volontaire
            </button>
          </div>
        </form>
        {% endif %}
      </div>
    </div>
  </div>

</div>

ateliersoude/user/templates/user/organization/modal_more_info.html
{% load bootstrap4 app_filters %}


<div class="modal" id="more-info-{{ anonymous_user.pk }}" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
        {% if anonymous_user %}
        Compléter les info de {{ anonymous_user }}
        {% else %}
        Ajouter un membre à l'organisation
        {% endif %}
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Veuillez compléter ces info s'il vous plait.
        <form
            {% if anonymous_user %}
            action="{% url 'user:organization_update_member' object.pk anonymous_user.pk %}"
            {% else %}
            action="{% url 'user:organization_add_member' object.pk %}"
            {% endif %}
            method="post"
            class="text-left"
        >
          <div class="modal-body">
            {% csrf_token %}
            {% bootstrap_form form=form %}
          </div>
          {% if object.fee_description %}
            <p>{{ object.fee_description }}</p>
          {% endif %}
          <p>
            <b>Note:</b>
            La contribution minimale pour cette organisation est de
            <span class="badge badge-pill badge-secondary">{{ object.min_fee }}€</span>
            et la contribution totale conseillée est de
            <span class="badge badge-pill badge-success">{{ object.advised_fee }}€</span>
            {% if anonymous_user and anonymous_user.first_name %}
              <br>
              {% filter_orga queryset=anonymous_user.memberships organization=object as membership %}
              {% if membership %}
                {{ anonymous_user }} a payé <span class="badge badge-pill badge-primary">{{ membership.current_contribution }}€</span> depuis le {{ membership.first_payment|date:"d F Y" }}
              {% else %}
                {{ anonymous_user }} n'a pas encore contribué pour <b>{{ object }}</b>
              {% endif %}
            {% endif %}
          </p>
          <div class="modal-footer">
            <input type="submit" value="Enregistrer" class="btn btn-primary">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

ateliersoude/user/templates/user/organization/organization_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% load assets app_filters %}

{% block extra_css %}
  {% assets "css_detail_organization" %}
    <link type="text/css" href="{{ ASSET_URL }}" rel="stylesheet"/>
  {% endassets %}
{% endblock %}

{% block content %}
  {% url "user:organization_list" as organization_list_url %}
  {% include "breadcrumb.html" with current=organization first_parent_url=organization_list_url first_parent_text="Organisations" %}

  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1>{{ organization.name }}</h1>
      {% if is_admin %}
        <a class="btn btn-success btn-sm" href="{% url 'user:organization_update' organization.id %}">
          <i class="fa fa-pencil-alt"></i> Editer
        </a>
        <a class="btn btn-danger btn-sm" href="{% url 'user:organization_delete' organization.id %}">
          <i class="fa fa-trash"></i> Supprimer
        </a>
        <a class="btn btn-primary btn-sm" href="{% url 'event:condition_create' organization.pk %}" title="create condition">
          <i class="fa fa-plus-circle"></i> Créer une condition d'accès
        </a>
        <a class="btn btn-primary btn-sm" href="{% url 'event:activity_create' organization.pk %}" title="activity place">
          <i class="fa fa-plus-circle"></i> Ajouter une activité
        </a>
        <a href="{% url 'location:create' organization.pk %}" class="btn btn-info btn-sm">
          <i class="fa fa-plus-circle"></i> Ajouter un local
        </a>
      {% endif %}
      {% if is_active %}
        <a class="btn btn-primary btn-sm{% if not organization.activities.all %} disabled{% endif %}" href="{% url 'event:create' organization.id %}">
          <i class="fa fa-plus-circle"></i> Créer un évènement
        </a>
        <a class="btn btn-primary btn-sm{% if not organization.activities.all %} disabled{% endif %}" href="{% url 'event:recurrent_create' organization.id %}">
          <i class="fa fa-plus-circle"></i> Créer un évènement récurrent
        </a>
      {% endif %}
    </div>
  </div>


  <section class="container">

    <h3>Description</h3>
    <div>
      {{ organization.description | safe }}
    </div>

    <h3 class="mt-4">Locaux</h3>
    {% if organization.places.all %}
      <div class="card-columns">
        {% for place in organization.places.all %}
          <div class="card">  
            <a class="card-link" href="{% url 'location:detail' place.pk place.slug %}">
              <div class="card-body">
                <h4 class="card-title">{{ place.name }}</h4>
                <h6 class="card-subtitle mb-2 text-muted">{{ place.address }}</h6>
                <span class="badge badge-secondary">{{ place.category }}</span>
                {{ place.description | safe | truncatewords_html:10 }}
              </div>
              {% if is_admin %}
                <div class="card-footer">
                  <a class="btn btn-info btn-sm" href="{% url 'location:edit' place.id %}">
                    <i class="fa fa-pencil-alt"></i>
                    Editer ce lieu
                  </a>
                  <a class="btn btn-danger btn-sm" href="{% url 'location:delete' place.id %}">
                    <i class="fa fa-trash-alt"></i>
                    Supprimer ce lieu
                  </a>
                </div>
              {% endif %}
            </a>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <div>Il n'y a pas de local associé à cette organisation.</div>
    {% endif %}


    <h3 class="mt-4">Membres volontaires</h3>


    {% include 'user/organization/manage_user.html' %}

    <div class="row mt-2">
      <div class="col-sm">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Les membres</h4>
            <ul class="list-group list-group-flush">
              {% for membership in organization.memberships.all %}
                {% if membership.user.is_visible or is_volunteer %}
                <li class="list-group-item">
                  <a href="{% url 'user:user_detail' membership.user.pk %}">
                    {{ membership.user }}
                  </a>
                  {% if membership.current_contribution > 0 %}
                    (A donné
                      <span class="badge badge-pill badge-secondary">
                      {{ membership.current_contribution }}€
                      </span>
                    depuis le {{ membership.first_payment|date:"d F Y" }})
                  {% endif %}
                  <button class="btn btn-success btn-sm" 
                          data-toggle="modal" 
                          data-target="#more-info-{{ membership.user.pk }}">
                    <i class="fa fa-plus"></i>
                    Mettre à jour le membre
                  </button>
                  <ul>
                    {% organization_fees organization membership.user as fees %}
                    {% for fee in fees %}
                      <li>
                        {{ fee.date }} - {{ fee.amount }} €
                      </li>
                    {% endfor %}
                  </ul>
                </li>
                {% include "user/organization/modal_more_info.html" with anonymous_user=membership.user form=add_member_form|initial:membership.user %}
                {% endif %}
                {% empty %}
                <li class="list-group-item">
                  Il n'y a pas de membre visible dans cette organisation
                </li>
              {% endfor %}
              <button class="btn btn-success btn-sm" 
                      data-toggle="modal" 
                      data-target="#more-info-">
                <i class="fa fa-plus"></i>
                Ajouter un membre
              </button>
              {% include "user/organization/modal_more_info.html" with form=add_member_form %}
            </ul>
          </div>
        </div>
      </div>
    </div>

    {% if events or has_hidden_events %}
      <h3 class="mt-4">Prochains évènements</h3>
      {% if is_volunteer %}
        <a href="{% url 'user:organization_all_events' organization.pk organization.slug page %}" class="btn btn-sm btn-info">
          <i class="fa fa-search"></i>
          Voir tous les évènements
        </a>
      {% endif %}
      <div class="card-columns">
        {% include "event/event_cards.html" with event_list=events %}
      </div>
    {% endif %}

    <h3 class="mt-4">Activités</h3>
    <div class="card-columns">
      {% include "event/activity/cards.html" with activities=organization.activities.all %}
    </div>
    {% if is_admin %}
      <div class="dropdown-divider mb-4"></div>
      <div class="row m-4">
        <h4>Conditions d'accès</h4>
      </div>
      <div class="card-columns">
        {% include 'event/condition/list.html' with conditions=organization.conditions.all %}
      </div>
    {% endif %}

  </section>

{% endblock %}

{% block extra_js %}
  {{ users|json_script:"users-data" }}
  {% assets "js_detail_organization" %}
    <script src="{{ ASSET_URL }}"></script>
  {% endassets %}
{% endblock %}

ateliersoude/user/templates/user/organization/organization_event_list.html
{% extends 'base.html' %}

{% block content %}
  {% url "user:organization_list" as organization_list_url %}
  {% url "user:organization_detail" organization.pk organization.slug  as organization_url %}
  {% include "breadcrumb.html" with current="Évènements" first_parent_url=organization_url first_parent_text=organization second_parent_url=organization_list_url second_parent_text="Organisations" %}

  <div class="container">
    <h1 class="mt-4 mb-4">Tous les évènements liés à {{ organization }}</h1>

    <div class="card-columns">
      {% include "event/event_cards.html" with event_list=event_list %}
    </div>

    {% if is_paginated %}
      <nav aria-label="Event navigation" class="mt-4">
        <ul class="pagination justify-content-center">
          <li class="page-item{% if paginator.has_previous %} disabled{% endif %}">
            <a class="page-link" href="{% url 'user:organization_all_events' organization.pk organization.slug page_obj.number|add:-1 %}" tabindex="-1">
              Previous
            </a>
          </li>

          {% for page in paginator.page_range %}
            <li class="page-item{% if page == page_obj.number %} active{% endif %}">
              <a class="page-link" href="{% url 'user:organization_all_events' organization.pk organization.slug page %}">
                {{ page }}
              </a>
            </li>
          {% endfor %}

          <li class="page-item{% if paginator.has_next %} disabled{% endif %}">
            <a class="page-link" href="{% url 'user:organization_all_events' organization.pk organization.slug page_obj.number|add:1 %}">
              Next
            </a>
          </li>
        </ul>
      </nav>
    {% endif %}
  </div>
{% endblock %}