ateliersoude/location/urls.py
from django.urls import path

from . import views

app_name = "location"
urlpatterns = [
    path("", views.PlaceMapView.as_view(), name="list"),
    path(
        "create/<int:orga_pk>", views.PlaceCreateView.as_view(), name="create"
    ),
    path("<int:pk>/edit/", views.PlaceEditView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.PlaceDeleteView.as_view(), name="delete"),
    path("<int:pk>/<slug>/", views.PlaceView.as_view(), name="detail"),
]

ateliersoude/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path("", views.HomeView.as_view(), name="homepage"),
    path("user/", include("ateliersoude.user.urls", namespace="user")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("event/", include("ateliersoude.event.urls", namespace="event")),
    path(
        "location/",
        include("ateliersoude.location.urls", namespace="location"),
    ),
    path(
        "api/location/",
        include("ateliersoude.location.api_urls", namespace="api_location"),
    ),
    path(r"tinymce/", include("tinymce.urls")),
]

if settings.DEBUG:
    import debug_toolbar  # noqa

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls))
    ] + urlpatterns

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

ateliersoude/location/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
from simple_history.models import HistoricalRecords

from ateliersoude.fields import CleanHTMLField

from ateliersoude.user.models import Organization
from ateliersoude.utils import validate_image, get_future_published_events


class Place(models.Model):
    name = models.CharField(max_length=100, verbose_name=_("Name"))
    organization = models.ForeignKey(
        Organization,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="places",
    )
    description = CleanHTMLField(
        default="", verbose_name=_("Place description")
    )
    category = models.CharField(max_length=100, default="Other")
    slug = models.SlugField(default="", blank=True)
    address = models.CharField(
        max_length=255, verbose_name=_("street address")
    )
    longitude = models.FloatField()
    latitude = models.FloatField()
    picture = models.ImageField(
        upload_to="places/",
        blank=True,
        null=True,
        validators=[validate_image],
        verbose_name=_("Image"),
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    history = HistoricalRecords()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("location:detail", args=(self.pk, self.slug))

    def future_published_events(self):
        return get_future_published_events(self.events)

    def __str__(self):
        return self.name

ateliersoude/location/forms.py
from django import forms
from django.forms import ModelForm

from ateliersoude.location.models import Place


class PlaceForm(ModelForm):
    longitude = forms.CharField(widget=forms.HiddenInput)
    latitude = forms.CharField(widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["picture"].widget.attrs.update({"class": "form-control"})

    class Meta:
        model = Place
        exclude = ["created_at", "updated_at", "slug", "owner", "organization"]

ateliersoude/location/views.py
from django.contrib import messages
from django.urls import reverse_lazy

from django.views.generic import (
    DetailView,
    TemplateView,
    DeleteView,
    CreateView,
    UpdateView,
)

from ateliersoude.location.forms import PlaceForm
from ateliersoude.location.models import Place
from ateliersoude.user.mixins import PermissionOrgaContextMixin
from ateliersoude.mixins import RedirectQueryParamView, HasAdminPermissionMixin


class PlaceView(PermissionOrgaContextMixin, DetailView):
    model = Place


class PlaceDeleteView(
    HasAdminPermissionMixin, RedirectQueryParamView, DeleteView
):
    model = Place
    success_url = reverse_lazy("location:list")

    def delete(self, request, *args, **kwargs):
        messages.success(request, "Le lieu a bien été supprimé")
        return super().delete(request, *args, **kwargs)


class PlaceMapView(TemplateView):
    template_name = "location/place_list.html"


class PlaceFormView(HasAdminPermissionMixin):
    def form_valid(self, form):
        form.instance.organization = self.organization
        messages.success(self.request, self.success_message)
        return super().form_valid(form)


class PlaceCreateView(RedirectQueryParamView, PlaceFormView, CreateView):
    form_class = PlaceForm
    model = Place
    success_message = "Le lieu a bien été créé"


class PlaceEditView(RedirectQueryParamView, PlaceFormView, UpdateView):
    form_class = PlaceForm
    model = Place
    success_message = "Le lieu a bien été modifié"

ateliersoude/location/templates/location/place_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  {% url "location:list" as location_list_url %}
  {% url "location:detail" place.pk place.slug as location_detail_url %}
  {% include "breadcrumb.html" with current="Suppression" second_parent_url=location_list_url second_parent_text="Lieux" first_parent_url=location_detail_url first_parent_text=place %}
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">
        Suppression de '{{ place }}'
      </h1>
    </div>
  </div>
  <section class="container">
    <p>
      <i class="fa fa-exclamation-triangle"></i>
      Vous êtes sur le point de supprimer le lieu <code>'{{ place }}'</code> situé à <code>'{{ place.address }}'</code>. Êtes-vous certain de votre choix ?
    </p>
    <form method="post">{% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-danger" type="submit">
        <i class="fa fa-trash"></i>
        Oui je suis sûr
      </button>
      <a class="btn btn-success" href="{% url 'location:detail' place.pk place.slug %}">
        <i class="fa fa-arrow-left"></i>
        Non, revenir
      </a>
    </form>
  </section>
{% endblock %}

ateliersoude/location/templates/location/place_detail.html
{% extends 'base.html' %}
{% load assets %}
{% load l10n %}

{% block extra_css %}
  {% assets "css_detail_place" %}
    <link type="text/css" href="{{ ASSET_URL }}" rel="stylesheet"/>
  {% endassets %}
{% endblock %}

{% block content %}
  {% url "location:list" as location_list_url %}
  {% include "breadcrumb.html" with current=place first_parent_url=location_list_url first_parent_text="Lieux" %}
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">{{ place.name|title }}</h1>
      {% if is_admin %}
      <p class="lead">
        <a class="btn btn-primary btn-sm" href="{% url 'location:edit' place.id %}">
          <i class="fa fa-pencil-alt"></i>
          Editer ce lieu
        </a>
        <a class="btn btn-danger btn-sm" href="{% url 'location:delete' place.id %}">
          <i class="fa fa-trash-alt"></i>
          Supprimer ce lieu
        </a>
      </p>
      {% endif %}
    </div>
  </div>
  <section class="container">
    <div class="card">
      {% if place.picture %}
        <img class="img-responsive w-100" src="{{ place.picture.url }}" alt="image_lieu">
      {% endif %}
      <div class="card-body">
        <h5 class="card-subtitle pb-3 mb-2 mt-2 text-muted border-bottom">
          {{ place.category }} -
          <small>
            <i class="fa fa-map-marker"></i>
            {{ place.address }}
          </small>
        </h5>
        {{ place.description | safe }}
      </div>
    </div>

    <div class="card">
      <div class="card-body">
        <h5 class="card-subtitle pb-3 mb-2 mt-2 text-muted border-bottom">Prochains évènements en ce lieu</h5>
        <ul>
          {% for event in place.future_published_events %}
            <li><a href="{% url 'event:detail' event.pk event.slug %}">{{ event }}</a></li>
            {% empty %}
            <i class="fa fa-calendar-times"></i>
            Aucun évènement planifié ici pour le moment
          {% endfor %}
        </ul>
      </div>
    </div>
  </section>
  <section class="container-fluid" id="place_map" style="height: 90vh"></section>

{% endblock %}

{% block extra_js %}
  <script>
    let latitude = {{ place.latitude|unlocalize }};
    let longitude = {{ place.longitude|unlocalize }};
    let placeName = "{{ place.name }}";
  </script>
  {% assets "js_detail_place" %}
    <script src="{{ ASSET_URL }}"></script>
  {% endassets %}
{% endblock %}

ateliersoude/location/templates/location/place_form.html
{% extends 'base.html' %}
{% load assets %}
{% load bootstrap4 %}

{% block extra_css %}
  {% assets "css_autocomplete" %}
    <link type="text/css" href="{{ ASSET_URL }}" rel="stylesheet"/>
  {% endassets %}
{% endblock %}

{% block content %}
  {% url "location:list" as location_list_url %}
  {% if place %}
    {% url "location:detail" place.pk place.slug as location_detail_url %}
    {% include "breadcrumb.html" with current="Mise à jour" second_parent_url=location_list_url second_parent_text="Lieux" first_parent_url=location_detail_url first_parent_text=place %}
  {% else %}
    {% include "breadcrumb.html" with current="Création" first_parent_url=location_list_url first_parent_text="Lieux" %}
  {% endif %}
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">
        {% if place %}
          Mise à jour de '{{ place }}'
        {% else %}
          Création d'un nouveau lieu
        {% endif %}
      </h1>
    </div>
  </div>
  <section class="container mt-4">
    <div class="card p-3">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="form-group p-2">
          <button type="submit" class="btn btn-success w-100 p-3">Valider</button>
        </div>
      </form>
    </div>
  </section>
{% endblock %}

{% block extra_js %}
  {{ form.media }}
  {% assets "js_create_edit_place" %}
    <script src="{{ ASSET_URL }}"></script>
  {% endassets %}
{% endblock %}

ateliersoude/location/templates/location/place_list.html
{% extends 'base.html' %}

{% load assets %}

{% block title %} {{ block.super }} Lieux {% endblock title %}

{% block extra_css %}
  {% assets "css_places" %}
    <link type="text/css" href="{{ ASSET_URL }}" rel="stylesheet"/>
  {% endassets %}
{% endblock %}

{% block content %}
  <section class="container-fluid">
    <div id="place_map"></div>
  </section>
{% endblock %}

{% block extra_js %}
  {% assets "js_places" %}
    <script src="{{ ASSET_URL }}"></script>
  {% endassets %}
{% endblock %}